version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: firebase
    versions:
    - 8.4.1
  - dependency-name: "@babel/core"
    versions:
    - 7.13.15
  - dependency-name: expo
    versions:
    - 41.0.0
